### ISSUE TITLE
Next release WhereYouGo

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/WhereYouGo#364]
We released 2022.01.14 with fixes for GPS on Android 12 and meeting the formal requirements of Google Play (TargetSDK=30).

However there is still work to be done and contributions needed for at least:
- [x] #368
- [x] #416
- [x] #412

No requirement for a new release, but nice to be included:
- [x] #391
- [x] #420 (related to #250)

In the long run the following items are a must-have, but those are pretty large tasks potentially, therefore we should not wait for them to release a new bugfix release:
- [ ] #309  WhereYouGo needs a modernized file access to be able to access offline maps and cartridges 
- [ ] #73 A newer mapsforge version is prerequisite to load files via SAF
- [x] #347 Will be solved implicitly when solving #73

Feel free to step into any of these (or other) issues and help keeping WhereYouGo alive!

**Comment by Lineflyer** [comment]
#368 added above

**Comment by moving-bits** [comment]
Added #416, #412 as prerequisites for next version, added #391 and #420 as "nice to have", and shuffled around the huge tasks of #309 and #73 as non-blocking for next release

IMHO we should release after the "must haves" (better: also the "nice to haves") have been merged and tested for a couple of days, as currently nobody can download a new cartridge due to the website changes behind #412.

**Comment by Lineflyer** [comment]
@moving-bits Was it intended to close this "next release" issue by your commit?

**Comment by moving-bits** [comment]
No, was caused by a wrong issue number in commit message (that's why 368 is still open). I'll reopen here, and close the other issue manually.

**Comment by Lineflyer** [comment]
As @moving-bits informed me a new release should be done for WhereYouGo. I will prepare this and (if not already there) will also document the needed steps in a wiki article.
I will try to find time during today or this evening.

Anything missing or can I just start?

**Comment by Lineflyer** [comment]
I am currently preparing everything for the release. Branches are already updates and release version is built.
I do however have to solve some warnings on Google Play...investigating:
![image](https://user-images.githubusercontent.com/949669/220591405-3d827eea-29b9-4b2d-bfe0-20fd21d1f52a.png)

**Comment by bekuno** [comment]
Strange - our targetSdk is 31.
Do we get such warning also for c:geo?

**Comment by Lineflyer** [comment]
I guess we would receive such warning also for c:geo.
But for c:geo I took the time last year to complete all guideline compliance questionnaires already.

For WhereYouGo I assume/hope we are not using any advertisement ID, so I will just click No for that and for government apps as well.

**Comment by Lineflyer** [comment]
Release process was already documented [here](https://github.com/cgeo/WhereYouGo/wiki/Release-preparation)

- [ ] Check/Insert correct version name as headline in `/src/main/assets/news.xml`.
- [ ] Check/Complete the versions changelog in `src/main/assets/news.xml` (will be shown in the app) 
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```whereyougo-release.apk``` before continuing
- [ ] Upload and publish ```whereyougo-release.apk``` to Google Play
- [ ] Tag the release on Github 
- [ ] Publish the release on Github including upload of ```whereyougo-release.apk``` to Github
- [ ] Post release info to Facebook as soon as update is available on Google Play

**Comment by Lineflyer** [comment]
Done here. Thanks for helping out to fix the critical things. I will take the remaining issues from the list above into a followup issue.
